In [1]:
import numpy as np
import pandas as pd

In [2]:
# colab으로 실행할 때
from google.colab import drive
drive.mount('/content/drive')
train_df = pd.read_csv('/content/drive/MyDrive/kaggle-study/1/data02/train.csv')
test_df = pd.read_csv('/content/drive/MyDrive/kaggle-study/1/data02/test.csv')
submission_df = pd.read_csv('/content/drive/MyDrive/kaggle-study/1/data02/submission_sample.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
train_df.head()

   inst_id    OC       sido  ...  employee1  employee2  ownerChange
0        1  open  choongnam  ...       62.0       64.0         same
1        3  open  gyeongnam  ...      801.0      813.0         same
2        4  open   gyeonggi  ...      234.0        1.0         same
3        7  open    incheon  ...      663.0      663.0         same
4        9  open  gyeongnam  ...      206.0      197.0         same

[5 rows x 58 columns]

train.csv - 의료기관이 폐업했는지 여부를 포함하여 최근 2개년의 재무정보와 병원 기본정보 

test.csv - 폐업 여부를 제외하고 train.csv와 동일 

sample_submission.csv - inst_id와 open과 close를 예측하는 OC 두개의 열로 구성. OC의 값은 open 예측일 경우 1, close 예측일 경우 0.



inst_id - 각 파일에서의 병원 고유 번호

OC – 영업/폐업 분류, 2018년 폐업은 2017년 폐업으로 간주함

sido – 병원의 광역 지역 정보

sgg – 병원의 시군구 자료

openDate – 병원 설립일

bedCount - 병원이 갖추고 있는 병상의 수

instkind – 병원, 의원, 요양병원, 한의원, 종합병원 등 병원의 종류

·        종합병원 : 입원환자 100명 이상 수용 가능

·        병원 : 입원 환자 30명 이상 100명 미만 수용 가능

·        의원 : 입원 환자 30명 이하 수용 가능

·        한방 병원(한의원) : 침술과 한약으로 치료하는 의료 기관.  

 

revenue1 – 매출액, 2017(회계년도)년 데이터를 의미함

salescost1 – 매출원가, 2017(회계년도)년 데이터를 의미함

sga1 - 판매비와 관리비, 2017(회계년도)년 데이터를 의미함

salary1 – 급여, 2017(회계년도)년 데이터를 의미함

noi1 – 영업외수익, 2017(회계년도)년 데이터를 의미함

noe1 – 영업외비용, 2017(회계년도)년 데이터를 의미함

Interest1 – 이자비용, 2017(회계년도)년 데이터를 의미함

ctax1 – 법인세비용, 2017(회계년도)년 데이터를 의미함

Profit1 – 당기순이익, 2017(회계년도)년 데이터를 의미함

liquidAsset1 – 유동자산, 2017(회계년도)년 데이터를 의미함

quickAsset1 – 당좌자산, 2017(회계년도)년 데이터를 의미함

receivableS1 - 미수금(단기), 2017(회계년도)년 데이터를 의미함

inventoryAsset1 – 재고자산, 2017(회계년도)년 데이터를 의미함

nonCAsset1 – 비유동자산, 2017(회계년도)년 데이터를 의미함

tanAsset1 – 유형자산, 2017(회계년도)년 데이터를 의미함

OnonCAsset1 - 기타 비유동자산, 2017(회계년도)년 데이터를 의미함

receivableL1 – 장기미수금, 2017(회계년도)년 데이터를 의미함

debt1 – 부채총계, 2017(회계년도)년 데이터를 의미함

liquidLiabilities1 – 유동부채, 2017(회계년도)년 데이터를 의미함

shortLoan1 – 단기차입금, 2017(회계년도)년 데이터를 의미함

NCLiabilities1 – 비유동부채, 2017(회계년도)년 데이터를 의미함

longLoan1 – 장기차입금, 2017(회계년도)년 데이터를 의미함

netAsset1 – 순자산총계, 2017(회계년도)년 데이터를 의미함

surplus1 – 이익잉여금, 2017(회계년도)년 데이터를 의미함

 

revenue2 – 매출액, 2016(회계년도)년 데이터를 의미함

salescost2 – 매출원가, 2016(회계년도)년 데이터를 의미함

sga2 - 판매비와 관리비, 2016(회계년도)년 데이터를 의미함

salary2 – 급여, 2016(회계년도)년 데이터를 의미함

noi2 – 영업외수익, 2016(회계년도)년 데이터를 의미함

noe2 – 영업외비용, 2016(회계년도)년 데이터를 의미함

interest2 – 이자비용, 2016(회계년도)년 데이터를 의미함

ctax2 – 법인세비용, 2016(회계년도)년 데이터를 의미함

profit2 – 당기순이익, 2016(회계년도)년 데이터를 의미함

liquidAsset2 – 유동자산, 2016(회계년도)년 데이터를 의미함

quickAsset2 – 당좌자산, 2016(회계년도)년 데이터를 의미함

receivableS2 - 미수금(단기), 2016(회계년도)년 데이터를 의미함

inventoryAsset2 – 재고자산, 2016(회계년도)년 데이터를 의미함

nonCAsset2 – 비유동자산, 2016(회계년도)년 데이터를 의미함

tanAsset2 – 유형자산, 2016(회계년도)년 데이터를 의미함

OnonCAsset2 - 기타 비유동자산, 2016(회계년도)년 데이터를 의미함

receivableL2 – 장기미수금, 2016(회계년도)년 데이터를 의미함

Debt2 – 부채총계, 2016(회계년도)년 데이터를 의미함

liquidLiabilities2 – 유동부채, 2016(회계년도)년 데이터를 의미함

shortLoan2 – 단기차입금, 2016(회계년도)년 데이터를 의미함

NCLiabilities2 – 비유동부채, 2016(회계년도)년 데이터를 의미함

longLoan2 – 장기차입금, 2016(회계년도)년 데이터를 의미함

netAsset2 – 순자산총계, 2016(회계년도)년 데이터를 의미함

surplus2 – 이익잉여금, 2016(회계년도)년 데이터를 의미함

employee1 – 고용한 총 직원의 수, 2017(회계년도)년 데이터를 의미함

employee2 – 고용한 총 직원의 수, 2016(회계년도)년 데이터를 의미함

ownerChange – 대표자의 변동

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 58 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   inst_id             301 non-null    int64
 1   OC                  301 non-null    object
 2   sido                301 non-null    object
 3   sgg                 301 non-null    int64
 4   openDate            301 non-null    int64
 5   bedCount            296 non-null    float64
 6   instkind            300 non-null    object
 7   revenue1            293 non-null    float64
 8   salescost1          293 non-null    float64
 9   sga1                293 non-null    float64
 10  salary1             293 non-null    float64
 11  noi1                293 non-null    float64
 12  noe1                293 non-null    float64
 13  interest1           293 non-null    float64
 14  ctax1               293 non-null    float64
 15  profit1             293 non-null    float64
 16  liquidAsset1        293 non-null    float64
 17  quickAsset1         293 non-null    float64
 18  receivableS1        293 non-null    float64
 19  inventoryAsset1     293 non-null    float64
 20  nonCAsset1          293 non-null    float64
 21  tanAsset1           293 non-null    float64
 22  OnonCAsset1         293 non-null    float64
 23  receivableL1        293 non-null    float64
 24  debt1               293 non-null    float64
 25  liquidLiabilities1  293 non-null    float64
 26  shortLoan1          293 non-null    float64
 27  NCLiabilities1      293 non-null    float64
 28  longLoan1           293 non-null    float64
 29  netAsset1           293 non-null    float64
 30  surplus1            293 non-null    float64
 31  revenue2            293 non-null    float64
 32  salescost2          293 non-null    float64
 33  sga2                293 non-null    float64
 34  salary2             293 non-null    float64
 35  noi2                293 non-null    float64
 36  noe2                293 non-null    float64
 37  interest2           293 non-null    float64
 38  ctax2               293 non-null    float64
 39  profit2             293 non-null    float64
 40  liquidAsset2        293 non-null    float64
 41  quickAsset2         293 non-null    float64
 42  receivableS2        293 non-null    float64
 43  inventoryAsset2     293 non-null    float64
 44  nonCAsset2          293 non-null    float64
 45  tanAsset2           293 non-null    float64
 46  OnonCAsset2         293 non-null    float64
 47  receivableL2        293 non-null    float64
 48  debt2               293 non-null    float64
 49  liquidLiabilities2  293 non-null    float64
 50  shortLoan2          293 non-null    float64
 51  NCLiabilities2      293 non-null    float64
 52  longLoan2           293 non-null    float64
 53  netAsset2           293 non-null    float64
 54  surplus2            293 non-null    float64
 55  employee1           291 non-null    float64
 56  employee2           288 non-null    float64
 57  ownerChange         289 non-null    object
dtypes: float64(51), int64(3), object(4)
memory usage: 136.5+ KB

# 데이터 전처리

## OC
1. open: 1, close: 0 라벨링

In [5]:
train_df['OC'].value_counts()

open      286
 close     15
Name: OC, dtype: int64

In [6]:
from sklearn.preprocessing import OrdinalEncoder

# fit_transform 의 인자로 trian[['OC']]를 넣는다. train_df['OC'] X 
# DataFrame이 반환되냐, Series가 반환되냐 의 차이
type(train_df['OC'])
type(train_df[['OC']])
OC_encoder = OrdinalEncoder()
OC_encoded = OC_encoder.fit_transform(train_df[['OC']])
train_df['OC'] = OC_encoded

In [7]:
train_df['OC'].value_counts()

1.0    286
0.0     15
Name: OC, dtype: int64

In [8]:
# 피처와 타겟값 분리
y = train_df['OC']
X = train_df.drop('OC', axis=1)

In [9]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 57 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   inst_id             301 non-null    int64
 1   sido                301 non-null    object
 2   sgg                 301 non-null    int64
 3   openDate            301 non-null    int64
 4   bedCount            296 non-null    float64
 5   instkind            300 non-null    object
 6   revenue1            293 non-null    float64
 7   salescost1          293 non-null    float64
 8   sga1                293 non-null    float64
 9   salary1             293 non-null    float64
 10  noi1                293 non-null    float64
 11  noe1                293 non-null    float64
 12  interest1           293 non-null    float64
 13  ctax1               293 non-null    float64
 14  profit1             293 non-null    float64
 15  liquidAsset1        293 non-null    float64
 16  quickAsset1         293 non-null    float64
 17  receivableS1        293 non-null    float64
 18  inventoryAsset1     293 non-null    float64
 19  nonCAsset1          293 non-null    float64
 20  tanAsset1           293 non-null    float64
 21  OnonCAsset1         293 non-null    float64
 22  receivableL1        293 non-null    float64
 23  debt1               293 non-null    float64
 24  liquidLiabilities1  293 non-null    float64
 25  shortLoan1          293 non-null    float64
 26  NCLiabilities1      293 non-null    float64
 27  longLoan1           293 non-null    float64
 28  netAsset1           293 non-null    float64
 29  surplus1            293 non-null    float64
 30  revenue2            293 non-null    float64
 31  salescost2          293 non-null    float64
 32  sga2                293 non-null    float64
 33  salary2             293 non-null    float64
 34  noi2                293 non-null    float64
 35  noe2                293 non-null    float64
 36  interest2           293 non-null    float64
 37  ctax2               293 non-null    float64
 38  profit2             293 non-null    float64
 39  liquidAsset2        293 non-null    float64
 40  quickAsset2         293 non-null    float64
 41  receivableS2        293 non-null    float64
 42  inventoryAsset2     293 non-null    float64
 43  nonCAsset2          293 non-null    float64
 44  tanAsset2           293 non-null    float64
 45  OnonCAsset2         293 non-null    float64
 46  receivableL2        293 non-null    float64
 47  debt2               293 non-null    float64
 48  liquidLiabilities2  293 non-null    float64
 49  shortLoan2          293 non-null    float64
 50  NCLiabilities2      293 non-null    float64
 51  longLoan2           293 non-null    float64
 52  netAsset2           293 non-null    float64
 53  surplus2            293 non-null    float64
 54  employee1           291 non-null    float64
 55  employee2           288 non-null    float64
 56  ownerChange         289 non-null    object
dtypes: float64(51), int64(3), object(3)
memory usage: 134.2+ KB

## ownerChange
1. 비어있는 값 -> 'unknown' 로 새로운 값 부여 -> 원핫인코딩

In [11]:
from sklearn.preprocessing import OneHotEncoder

X['ownerChange'][X['ownerChange'].isnull()] = 'unknown'
ownerChange_encoder = OneHotEncoder()
ownerChange_encoded = ownerChange_encoder.fit_transform(X[['ownerChange']])
X['ownerChange'] = ownerChange_encoded

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

## instkind
1. 비어있는 값 -> 가장 많은 값으로 -> 원핫인코딩

In [ ]:
X['instkind'][X['instkind'].isnull()] = X['instkind'].value_counts().index[0]
instkind_encoder = OneHotEncoder()
instkind_encoded = instkind_encoder.fit_transform(train_df[['instkind']])
train_df['instkind'] = instkind_encoded

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

## sido, sgg
1. 원핫인코딩

In [12]:
sido_encoder = OneHotEncoder()
sgg_encoder = OneHotEncoder()

sido_encoded = sido_encoder.fit_transform(train_df[['sido']])
sgg_encoded = sgg_encoder.fit_transform(train_df[['sgg']])


train_df['sido'] = sido_encoded
train_df['sgg'] = sgg_encoded

y = train_df['OC'].values
X = train_df.drop(['OC'], axis=0)

## 그외 숫자 피처들
1. 비어있는 값 -> 평균값

In [13]:
num_attribs = ['openDate', 'bedCount',
       'revenue1', 'salescost1', 'sga1', 'salary1', 'noi1', 'noe1',
       'interest1', 'ctax1', 'profit1', 'liquidAsset1', 'quickAsset1',
       'receivableS1', 'inventoryAsset1', 'nonCAsset1', 'tanAsset1',
       'OnonCAsset1', 'receivableL1', 'debt1', 'liquidLiabilities1',
       'shortLoan1', 'NCLiabilities1', 'longLoan1', 'netAsset1', 'surplus1',
       'revenue2', 'salescost2', 'sga2', 'salary2', 'noi2', 'noe2',
       'interest2', 'ctax2', 'profit2', 'liquidAsset2', 'quickAsset2',
       'receivableS2', 'inventoryAsset2', 'nonCAsset2', 'tanAsset2',
       'OnonCAsset2', 'receivableL2', 'debt2', 'liquidLiabilities2',
       'shortLoan2', 'NCLiabilities2', 'longLoan2', 'netAsset2', 'surplus2',
       'employee1', 'employee2']

In [14]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

num_pipeline = Pipeline([
  ('imputer', SimpleImputer(strategy='mean'))                        
])

In [15]:
from sklearn.compose import ColumnTransformer

col_transformer = ColumnTransformer([
  ('num', num_pipeline, num_attribs)                                     
])

X_processed = col_transformer.fit_transform(X)

In [17]:
X_processed.shape

(301, 52)

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

rnd_clf = RandomForestClassifier(n_jobs=-1)
accuracy = cross_val_score(rnd_clf, X_processed, y, scoring='accuracy')

In [20]:
accuracy

array([0.95081967, 0.91666667, 0.95      , 0.91666667, 0.93333333])

In [21]:
np.mean(accuracy)

0.9334972677595628